### ISSUE TITLE
Unable to set recurrence rule for Nth of every month

### ISSUE THREAD

**Issue by SteveHere** [jazzband/django-recurrence#160]
Proof (Unable to set a new rule for the Nth of every month):
![image](https://user-images.githubusercontent.com/13937978/73323638-0dece780-4283-11ea-8176-ca617e2dd9ce.png)

However, I can set the 'On the first X' with no problems:
![image](https://user-images.githubusercontent.com/13937978/73323693-396fd200-4283-11ea-91fb-f268ce808225.png)

JS error message:
![image](https://user-images.githubusercontent.com/13937978/73323403-522bb800-4282-11ea-9d86-e723df32b4d0.png)

Running breakpoints show that some attribute from recurrence called 'langauge_code' was supposed to be called over, but it doesn't exist:
![image](https://user-images.githubusercontent.com/13937978/73323529-afc00480-4282-11ea-8f01-e91acd37e113.png)

**Comment by SteveHere** [comment]
Found temporary fix by simply running `recurrence.language_code = "en"`

**Comment by SteveHere** [comment]
Okay, so... `recurrence.language_code` wasn't set in `recurrence.js`, that part's certain... now comes the problem of trying to set `recurrence.language_code`. 

I'm entering from a point of direct face-to-wall here, but the only way for `language_code` to be flexible would be to have it as a `SETTINGS` variable for users to hook a view to. And then call the view user-side, which will resolve what the `language_code` would be.

**Comment by derpadoo** [comment]
Seeing something similar.

```
Python 3.6
Django==2.2.10
django-recurrence==1.10.1
```

Trying to set a recurrence for the 1st and 15th of the month through the Django Admin.

![image](https://user-images.githubusercontent.com/27816854/76356980-d68f4300-62e4-11ea-9ea6-4406e419b82d.png)

The POST request inspected using DevTools (data isn't being passed correctly):

![image](https://user-images.githubusercontent.com/27816854/76357002-e149d800-62e4-11ea-941f-680e07639f87.png)

The result

![image](https://user-images.githubusercontent.com/27816854/76357014-e4dd5f00-62e4-11ea-8ef8-cf579d49a1e9.png)

I can modify it using a Django Rest Framework API endpoint by setting the payload as:

```python
'recurrences': 'RRULE:FREQ=MONTHLY;BYMONTHDAY=1,15\nRDATE:20200315T050000Z'
```

which makes it look like it is a javascript issue, but I'm not able to debug that.

**Comment by derpadoo** [comment]
My weak attempt to debug some javascript :)

In my example, it makes it to this line:

https://github.com/django-recurrence/django-recurrence/blob/master/recurrence/static/recurrence/js/recurrence.js#L158

but doesn't get to assign it to `items`

https://github.com/django-recurrence/django-recurrence/blob/master/recurrence/static/recurrence/js/recurrence.js#L161

![image](https://user-images.githubusercontent.com/27816854/76361995-2fafa480-62ee-11ea-95f0-aa1be5c0218e.png)

**Comment by derpadoo** [comment]
Traced the bug to where @SteveHere originally identified it in: https://github.com/django-recurrence/django-recurrence/blob/master/recurrence/static/recurrence/js/recurrence.js#L448

French language logic was added by @ollb in PR https://github.com/django-recurrence/django-recurrence/pull/32

Release was 1.2.0

![image](https://user-images.githubusercontent.com/27816854/76430218-10f8ee80-637e-11ea-8ba6-f24dde481fe7.png)

**Comment by lino** [comment]
This was fixed in https://github.com/jazzband/django-recurrence/commit/7190d6ca1f20fb248d516f1b405d0d9ff4b84e18
