### ISSUE TITLE
Form not displaying

### ISSUE THREAD

**Issue by redy007** [jazzband/django-recurrence#165]
Django 3.0, all requiments installed.

settings:
LANGUAGE_CODE = 'cs'

LANGUAGES = (
    ('cs', 'Čeština'),
    ('en', 'English'),
)

template:
{% csrf_token %}
{{ form.media }}
{{ form }}

javascript error:
TypeError: MutationObserver.observe: Argument 1 is not an object. recurrence-widget.init.js:7:11
    <anonymous> https://localhost:8000/static/recurrence/js/recurrence-widget.init.js:7
    jQuery 2
        mightThrow
        process

Please, can you help me?

**Comment by will-emmerson** [comment]
I had the same problem, it's looking for an element with an id of `container` so just put one in your html somewhere.
