### ISSUE TITLE
Recurrence only working in Admin but buttons don't do anything when I use it in Model Form

### ISSUE THREAD

**Issue by wolfhound115** [jazzband/django-recurrence#170]
Django admin has been fully functional with the package. However, when I tried to integrate it into a model form, the buttons don't do anything when I click them... Any help on this would be great because I've been stuck on this issue for days now with no luck!

**Comment by wolfhound115** [comment]
UPDATE: I got it to work by copying the head tag from the admin view into my form view, so it's definitely an issue of form.media not working correctly and not loading the full set of JS links required to run the form (although it does load some of the required JS/CSS)

**Comment by NZemlin** [comment]
Would you mind further specifying how you fixed this issue?  What do you mean by you copied the head tag from the admin view into your form view?  I'm having the same issue and am having trouble fixing it.  I'm pretty new to Django, so if this is a trivial question I apologize for the inconvenience

**Comment by wolfhound115** [comment]
Hey! Yeah I'd be happy to help.

What I meant by that is the recurrence package worked for me when i went into the django admin http://127.0.0.1:8000/admin

but for some reason I wasn't getting the functionality at all when I included it in a custom django model form.

So after spending days looking online for a solution I tried just going into the source code of the admin site on chrome by using inspect element and copied the tags inside the head tag to see if there was something the admin was loading that my custom form wasn't getting directly from the package from {% load static %} and {{ form.media }} (which ideally should be sufficient in getting it to work)
 
Initially, this is everything I copied from the <head> of the source code:


<head>
--
  | <title>Add just recurrence \| Django site admin</title>
  | <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
  | <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
  |  
  |  
  | <script type="text/javascript" src="/admin/jsi18n/"></script>
  | <link href="/static/recurrence/css/recurrence.css" type="text/css" media="all" rel="stylesheet">
  | <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
  | <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
  | <script type="text/javascript" src="/static/admin/js/core.js"></script>
  | <script type="text/javascript" src="/static/recurrence/js/recurrence.js"></script>
  | <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
  | <script type="text/javascript" src="/static/recurrence/js/recurrence-widget.js"></script>
  | <script type="text/javascript" src="/static/admin/js/actions.js"></script>
  | <script type="text/javascript" src="/static/recurrence/js/recurrence-widget.init.js"></script>
  | <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
  | <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
  | <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
  |  
  |  
  | <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
  | <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
  |  
  |  
  | <meta name="robots" content="NONE,NOARCHIVE">
  | </head>


And after trial and error of deleting things I came to the conclusion that these are the 4 tags necessary to get the recurrence package to work for me in my custom form (after already following all of the instructions in the documentation)

<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>

I hope this helps!

**Comment by wolfhound115** [comment]
Sorry for some reason it was reformatting my code every time I copied the tags so I had to take a screenshot*

**Comment by NZemlin** [comment]
Thank you! That did the trick, and I'm kicking myself for not thinking of that.  I appreciate your time very much.

**Comment by wolfhound115** [comment]
> Thank you! That did the trick, and I'm kicking myself for not thinking of that. I appreciate your time very much.

aw no worries fam! this is my first time helping someone out on github so I'm glad I could return a favor to the community! It was super frustrating when I spent days looking for an answer on every possible website without being able to find anything.

**Comment by NZemlin** [comment]
Did you follow wolfhound115's solution and it still didn't work for you? I included those head tags that he found and it started working immediately for me.

**Comment by jmaas** [comment]
Hi, thanks for the suggestion. I fixed it by adding a Media class to the form:
```python
    class Media:
        css = {'all': ('/static/admin/css/base.css', '/static/admin/css/forms.css',),}
        js = ('/admin/jsi18n', '/admin/js/core.js',)

**Comment by wolfhound115** [comment]
Hey guys, I found where the issue was in the source code and made a pull request for the bugfix if you'd like to check it out! My first time contributing a little to an open-source project so it took a little while for me to figure out where the issue was, but I'm glad I could help you guys out in the meantime!

https://github.com/django-recurrence/django-recurrence/pull/177

**Comment by tobast** [comment]
I've just encountered this issue in one of my projects. According to [the docs](https://docs.djangoproject.com/en/3.1/topics/i18n/translation/#internationalization-in-javascript-code), it seems that this project should provide a `JavaScriptCatalog` view. Reusing the admin site's `JavaScriptCatalog` looks like something that is not meant to be done and would be fragile.
