### ISSUE TITLE
Wagtail Error

### ISSUE THREAD

**Issue by ronaldlangeveld** [jazzband/django-recurrence#198]
Tried adding Django-recurrence to my Wagtail project... however getting the following.

<img width="930" alt="Screenshot 2022-03-04 at 14 00 19" src="https://user-images.githubusercontent.com/19263291/156759889-f46d5637-9d95-4413-afde-4236afe10574.png">

I suspect it might be caused by Wagtail running  ReactJS now that's messing with the compatibility.

**Comment by ronaldlangeveld** [comment]
https://github.com/wagtail/wagtail/issues/8078#issuecomment-1059745864

**Comment by lino** [comment]
This should be fixed with https://github.com/jazzband/django-recurrence/commit/b79551cccfad58cec664a806f70483ac67c22f66
