### ISSUE TITLE
Remove use of deprecated ‘distutils’ library

### ISSUE THREAD

**Issue by bignose-debian** [jazzband/django-recurrence#253]
Python versions from 3.10 onward [deprecate use of ‘distutils’ (in PEP 632)](https://peps.python.org/pep-0632/), and it will be removed from Python 3.12.

This project should remove the option for ‘distutils’, and commit to use only the recommended ‘setuptools’ for building the package.

**Comment by bignose-debian** [comment]
I have implemented changes to fix this issue, in branch [wip/issue/253/distutils-deprecated](https://salsa.debian.org/bignose/django-recurrence/-/tree/wip/issue/253/distutils-deprecated) of my personal fork repository.

The branch merges cleanly to [current 'master' branch](/jazzband/django-recurrence/commit/d4d00d2ba9d2b510e947cb94f954b5e73b740f76).

**Comment by lino** [comment]
I think with the move to pdm this should be obsolete.

**Comment by bignose-debian** [comment]
> I think with the move to pdm this should be obsolete.

If you mean that this project will cease using Distutils entirely, and instead build using [PDM](https://pdm-project.org/), then yes I think that will resolve this issue.

I see in [commit 6159bbcb](/jazzband/django-recurrence/commit/6159bbcb247699b2c0eaffbeeb81d2a06aa17956) that the build system changes to:

```toml
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```

which avoids Distutils for build.
