### ISSUE TITLE
Support creation meetings in the past (via DTSTART)

### ISSUE THREAD

**Issue by striveforbest** [jazzband/django-recurrence#293]
There is no way to create meetings in the past (think when updating a recurring meeting and selecting "All Meetings" on save in any calendar app).
![Uploading Screenshot 2024-06-20 at 10.25.49 AM.png…]()

Per [RFC 5545](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html), the start datetime can be provided in the recurrence like so:

1. Daily for 10 occurrences:
```
 DTSTART;TZID=America/New_York:19970902T090000
 RRULE:FREQ=DAILY;COUNT=10
```

resulting in
```
 ==> (1997 9:00 AM EDT) September 2-11
```

2. Daily until December 24, 1997:
```
 DTSTART;TZID=America/New_York:19970902T090000
 RRULE:FREQ=DAILY;UNTIL=19971224T000000Z
```
resulting in
```
 ==> (1997 9:00 AM EDT) September 2-30;October 1-25
     (1997 9:00 AM EST) October 26-31;November 1-30;December 1-23
```

**Comment by lino** [comment]
Hey, somehow your Screenshot did not upload (or I'm too thick to get it to show), I guess you're talking about the widget?

**Comment by striveforbest** [comment]
> Hey, somehow your Screenshot did not upload (or I'm too thick to get it to show), I guess you're talking about the widget?

Hmmm, something went wrong with the screenshot, unfortunately. But no, I'm not talking about the widget specifically. Overall the library doesn't support creating meetings in the past via DTSTART.

**Comment by striveforbest** [comment]
can't replicate rn, i'll close for now, thanks.
