### ISSUE TITLE
Widget should using JQuery or Something

### ISSUE THREAD

**Issue by emperorcezar** [jazzband/django-recurrence#4]
Currently the widget is very homegrown. It works great, but is difficulty to grep and modify. I propose a rewrite into JQuery/Backbone or something to keep the widget code minimal and maintainable.

**Comment by beruic** [comment]
I don't think this is a good idea. Relying on third party client side libs is an inconvenience and possibly nuisance for the user of this project and may contribute to bloating a project's use of third party client side libs. 

Alternatively do it default with Ajax refreshing to make it simple, and create an API for widgets so people can submit widgets for different frameworks. For example I hope to build a React widget using Bootstrap at some point.

**Comment by lino** [comment]
The widget was rewritten to jQuery and the concerns of @beruic were true.
