### ISSUE TITLE
prompts unsaved changes warning 

### ISSUE THREAD

**Issue by amirasaad** [jazzband/django-recurrence#86]
On submitting the main form browser prompts unsaved changes warning when rule or date was added.
It's bad for user experience 

It seems that in every single rule or date a form tag was used, I guess that what causes this bad experience or I made something wrong?

**Comment by dominicrodger** [comment]
What generates the unsaved changes warning? Is that some JavaScript on your side? I don't think that's the browser.

**Comment by amirasaad** [comment]
I modified the widget by javascript. Is there any other way to enable only on rule?

**Comment by dominicrodger** [comment]
Thanks for getting back to me @amirasaad! So it's your JavaScript that generated the warning about unsaved changes? I'm not sure what you're asking us to fix or change here - could you help me out?

**Comment by amirasaad** [comment]
This code snippet
```
recurrence = RecurrenceField(
        frequencies=(recurrence.WEEKLY,),
        max_rrules=1, max_rdates=30, max_exrules=0, max_exdates=0)
```
Generate something like that:
![img](https://django-recurrence.readthedocs.io/en/latest/_images/admin.png)

I want to customize this widget to show only Weekly and some other to be consistent with field options.

**Comment by dominicrodger** [comment]
Sorry @amirasaad - I'm a bit confused - that seems like a different request. Are you still having problems with the browser prompting you about unsaved changes?

I have no particular problem with an enhancement to limit which frequencies are accepted, if that's something you (or someone else) wants to work on.

**Comment by amirasaad** [comment]
Thanks for your reply. I think it would be a good feature.

and its a nice app btw
cheers
